language: ruby

services:
  - postgresql

before_script:
  - psql -U postgres -c 'CREATE DATABASE chitter_test;'

script:
  - psql -U postgres -c 'CREATE TABLE peeps (id SERIAL PRIMARY KEY, peep VARCHAR(240), posted_time VARCHAR(16));'
  - psql -U postgres -c 'CREATE TABLE users (id SERIAL PRIMARY KEY, email VARCHAR(60), password VARCHAR(140));'
  - psql -U postgres -c 'ALTER TABLE peeps ADD COLUMN posted_by VARCHAR(60);'
  - bundle exec rspec
