language: ruby

services:
  - postgresql

before_script:
  - psql -U postgres -c 'CREATE DATABASE chitter_test;'
  - psql --dbname=$chitter_test --file=db/migrations/01_create_peeps_table.sql

script:
  - bundle exec rspec
